using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using UnityEngine;
using VRC.SDK3.Avatars.ScriptableObjects;

namespace YagihataItems.RadialInventorySystemV4
{
    public static class RIS
    {
        private const string workFolderPath = "Assets/YagihataItems/RadialInventorySystemV4/";
        public static string WorkFolderPath 
        { 
            get 
            { 
                if (!Directory.Exists(workFolderPath))
                    Directory.CreateDirectory(workFolderPath); 
                return workFolderPath; 
            }
        }
        public static string AutoGeneratedFolderPath { get { return WorkFolderPath + "AutoGenerated/"; } }
        public static string RISV4SettingsPath { get { return WorkFolderPath + "RISV4Settings.json"; } }
        public const string SettingsFileName = "settings.json";
        public const string CurrentVersion = "ris_v4.6";
        public const string SettingsNameV3 = "RISV3Settings";
        public const string SettingsNameV4 = Prefix + "Settings";
        public const string Prefix = "RISV4";
        public const string VersionUrl = "https://www.negura-karasu.net/radialinventory/vercheck/";
        public const string DonatorListUrl = "https://www.negura-karasu.net/radialinventory/donators/";
        public const string ManualUrl = "https://negura-karasu.net/archives/1691";
        public const string TwitterUrl = "https://twitter.com/Yagihata4x";
        public const string DiscordURL = "https://discord.com/invite/HpsycV2zt7";
        public const string DownloadUrl = "https://yagihata.booth.pm/items/2278448";
        public const string AdsUrl = "https://negura-karasu.net/radialinventory/ads/";
        public const string PRUrl = "https://yagihata.fanbox.cc/posts/4256456";
        public const VRCExpressionParameters.ValueType IntParam = VRCExpressionParameters.ValueType.Int;
        public const VRCExpressionParameters.ValueType BoolParam = VRCExpressionParameters.ValueType.Bool;
        public const string LanguageFileGUID = "1162cc816f6898b46814462fd6c8d583";
        public const string WidthFileGUID = "e6414220d1e17a4409a92e50d8286260";
        public enum MenuModeType
        {
            Simple,
            Basic,
            Advanced
        }
        public enum ExclusiveGroupType
        {
            None = -1,
            Group1 = 0,
            Group2 = 1,
            Group3 = 2,
            Group4 = 3,
            Group5 = 4,
            Group6 = 5,
            Group7 = 6,
            Group8 = 7,
        }
        public enum BoneType
        {
            None,
            Head
        }
        public enum ExclusiveModeType
        {
            None,
            Exclusive,
            LegacyExclusive
        }
        public enum MaterialAnimationType
        {
            MaterialOnly = 0,
            Difference = 1,
            All = 2
        }
        public enum ParameterTriggerType
        {
            TurnON = 0,
            TurnOFF = 1
        }
    }
}
