using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using UnityEditor;
using UnityEngine;
using VRC.SDK3.Avatars.ScriptableObjects;

namespace YagihataItems.RadialInventorySystemV3
{
    public static class RISV3
    {
        public const string WorkFolderPath = "Assets/YagihataItems/RadialInventorySystemV3/";
        public const string AutoGeneratedFolderPath = WorkFolderPath + "AutoGenerated/";
        public const string CurrentVersion = "ris_dev";
        public const string SettingsName = "RISV3Settings";
        public const string VersionUrl = "https://www.negura-karasu.net/radinv_vercheck/";
        public const string ManualUrl = "https://www.negura-karasu.net/archives/1432";
        public const string TwitterUrl = "https://twitter.com/Yagihata4x";
        public const VRCExpressionParameters.ValueType IntParam = VRCExpressionParameters.ValueType.Int;
        public const VRCExpressionParameters.ValueType BoolParam = VRCExpressionParameters.ValueType.Bool;
        public enum RISMode
        {
            Simple,
            Advanced
        }
        public enum PropGroup
        {
            None,
            Group1,
            Group2,
            Group3,
            Group4,
            Group5,
            Group6,
            Group7,
            Group8,
        }
    }
}
