using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using UnityEngine;
#if UNITY_EDITOR
using UnityEditor;
using UnityEditor.PackageManager.Requests;
using UnityEditor.PackageManager;
#endif
using VRC.SDK3.Avatars.ScriptableObjects;

namespace YagihataItems.RadialInventorySystemV4
{
    public static class RIS
    {
        public const string WorkFolderPath = "Assets/YagihataItems/RadialInventorySystemV4/";
        public const string AutoGeneratedFolderPath = WorkFolderPath + "AutoGenerated/";
        public const string SettingsFileName = "settings.json";
        public const string CurrentVersion = "ris_v4.0_tesing";
        public const string SettingsNameV3 = "RISV3Settings";
        public const string SettingsNameV4 = Prefix + "Settings";
        public const string Prefix = "RISV4";
        public const string VersionUrl = "https://www.negura-karasu.net/radialinventory/vercheck/";
        public const string DonatorListUrl = "https://www.negura-karasu.net/radialinventory/donators/";
        public const string ManualUrl = "https://www.negura-karasu.net/archives/1456";
        public const string TwitterUrl = "https://twitter.com/Yagihata4x";
        public const string DownloadUrl = "https://yagihata.booth.pm/items/2278448";
        public const VRCExpressionParameters.ValueType IntParam = VRCExpressionParameters.ValueType.Int;
        public const VRCExpressionParameters.ValueType BoolParam = VRCExpressionParameters.ValueType.Bool;
        public enum MenuModeType
        {
            Simple,
            Basic,
            Advanced
        }
        public enum ExclusiveGroupType
        {
            None = -1,
            Group1 = 0,
            Group2 = 1,
            Group3 = 2,
            Group4 = 3,
            Group5 = 4,
            Group6 = 5,
            Group7 = 6,
            Group8 = 7,
        }
        public enum BoneType
        {
            None,
            Head
        }
        public enum ExclusiveModeType
        {
            None,
            Exclusive,
            LegacyExclusive
        }
#if UNITY_EDITOR
        [InitializeOnLoadMethod]
        static void CheckPackages()
        {
            Client.Add("com.unity.nuget.newtonsoft-json");
        }
#endif
    }
}
