using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;
using VRC.SDK3.Avatars.Components;
using YagihataItems.YagiUtils;

namespace YagihataItems.RadialInventorySystemV4
{
    [JsonObject]
    public class Avatar
    {
        [JsonProperty] public string UniqueID { get;  private set; }
        [JsonProperty] public GUIDPathPair<VRCAvatarDescriptor> AvatarRoot { get; set; }
        [JsonProperty] public bool UseWriteDefaults { get; set; } = false;
        [JsonProperty] public bool OptimizeParameters { get; set; } = true;
        [JsonProperty] public bool ApplyEnableDefault { get; set; } = true;
        [JsonProperty] public List<Group> Groups { get; set; } = new List<Group>();
        private RIS.ExclusiveModeType[] _exclusiveModes;
        [JsonProperty("changeTypes", ItemConverterType = typeof(StringEnumConverter))] public RIS.ExclusiveModeType[] ExclusiveModes { get { return _exclusiveModes; } set { _exclusiveModes = value; } }

        [JsonConverter(typeof(StringEnumConverter))] [JsonProperty] public RIS.MenuModeType MenuMode = RIS.MenuModeType.Simple;
        public Avatar()
        {
            AvatarRoot = new GUIDPathPair<VRCAvatarDescriptor>(ObjectPathStateType.Scene);
            UniqueID = Guid.NewGuid().ToString();
        }
        public void SetExclusiveMode(RIS.ExclusiveGroupType group, RIS.ExclusiveModeType type)
        {
            ResizeExclusiveModesArray();
            if (group != RIS.ExclusiveGroupType.None)
                ExclusiveModes[(int)group] = type;
        }
        public RIS.ExclusiveModeType GetExclusiveMode(RIS.ExclusiveGroupType group)
        {
            ResizeExclusiveModesArray();
            if (group == RIS.ExclusiveGroupType.None)
                return RIS.ExclusiveModeType.None;
            return ExclusiveModes[(int)group];
        }
        private void ResizeExclusiveModesArray()
        {
            var modeCount = Enum.GetNames(typeof(RIS.ExclusiveGroupType)).Length - 1;
            if (ExclusiveModes == null)
                ExclusiveModes = new RIS.ExclusiveModeType[modeCount];
            else if (ExclusiveModes.Length != modeCount)
                Array.Resize(ref _exclusiveModes, modeCount);
        }
        public void SaveToJson()
        {
            if (string.IsNullOrEmpty(UniqueID))
                UniqueID = Guid.NewGuid().ToString();
            var folderPath = RIS.AutoGeneratedFolderPath + UniqueID + "/";
            var jsonPath = $"{folderPath}{RIS.SettingsFileName}";
            if (!AssetDatabase.IsValidFolder(folderPath))
                UnityUtils.CreateFolderRecursively(folderPath);

            var jsonData = JsonConvert.SerializeObject(this, Formatting.Indented);
            using (var sw = new StreamWriter(jsonPath, false, Encoding.UTF8))
            {
                sw.Write(jsonData);
            }
        }
        public static Avatar LoadFromJson(string path)
        {
            var avatar = new Avatar();

            if (!File.Exists(path))
                throw new FileNotFoundException();

            using (var sr = new StreamReader(path, Encoding.UTF8))
            {
                var jsonData = sr.ReadToEnd();
                avatar = JsonConvert.DeserializeObject<Avatar>(jsonData);
            }
            return avatar;
        }
    }
}