using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using UnityEngine;

namespace YagihataItems.RadialInventorySystemV4
{
    public abstract class EditorTab
    {
        public abstract void InitializeTab(ref Avatar risAvatar);
        public abstract void DrawTab(ref Avatar risAvatar, Rect position, bool showingVerticalScroll);
        public abstract string[] CheckErrors(ref Avatar risAvatar);
        public abstract void BuildFXLayer(ref Avatar risAvatar, string autoGeneratedFolder);
    }
}
