using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using VRC.SDK3.Avatars.ScriptableObjects;

namespace YagihataItems.RadialInventorySystemV3
{
    public static class RISV3
    {
        public const string workFolderPath = "Assets/YagihataItems/RadialInventorySystemV3/";
        public const string autoGeneratedFolderPath = workFolderPath + "AutoGenerated/";
        public const string currentVersion = "radinv_v3.1";
        public const string settingsName = "RISV3Settings";
        public const string versionUrl = "https://www.negura-karasu.net/radinv_vercheck/";
        public const string manualUrl = "https://www.negura-karasu.net/archives/1432";
        public const string twitterUrl = "https://twitter.com/Yagihata4x";
        public const VRCExpressionParameters.ValueType IntParam = VRCExpressionParameters.ValueType.Int;
        public const VRCExpressionParameters.ValueType BoolParam = VRCExpressionParameters.ValueType.Bool;
    }
}
